name: Move Project Card on Issue Close

on:
  issues:
    types: [closed]

jobs:
  move-closed-issue-to-done:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to Done
        uses: fojia/action-move-issues-to-column@master
        with:
          project: 'Model Pipeline – Election Classifier' 
          column: 'Done'
          owner: 'alvess-dev'
          repo: 'election-news-classifier'
          type: 'repo'
          github_token: ${{ secrets.GITHUB_TOKEN }}
